DROP TABLE IF EXISTS users,
    categories,
    compilations,
    locations,
    events,
    requests,
    compilation_events,
    likes CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(300)                            NOT NULL,
    email     VARCHAR(320)                            NOT NULL,
    rate      FLOAT,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(300)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT uq_category_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(300)                            NOT NULL,
    pinned         BOOLEAN,
    CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat         FLOAT,
    lon         FLOAT,
    CONSTRAINT pk_clocation PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(1000)                           NOT NULL,
    category_id        BIGINT REFERENCES categories (category_id) ON DELETE CASCADE,
    confirmed_requests INTEGER,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(5000),
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator_id       BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    location_id        BIGINT REFERENCES locations (location_id) ON DELETE CASCADE,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    event_state        VARCHAR(100),
    title              VARCHAR(150)                            NOT NULL,
    rate               FLOAT,
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE,
    event_id     BIGINT REFERENCES events (event_id) ON DELETE CASCADE,
    requester_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    status       VARCHAR(100),
    CONSTRAINT pk_request PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE CASCADE,
    FOREIGN KEY (compilation_id) REFERENCES compilations (compilation_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes
(
    like_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id    BIGINT REFERENCES events (event_id) ON DELETE CASCADE,
    user_id     BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    is_positive BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_like PRIMARY KEY (like_id)
);
